---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hippo-deployment
  labels:
    app: hippo-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hippo-devops-project
  template:
    metadata:
      labels:
        app: hippo-devops-project 
    spec:
      containers:
      - name: nodeserver
        image: dockerpandian/project:latest
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: hippo-service
spec:
  selector:
    app: hippo-devops-project 
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
