---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: alweterdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: alweter
 template:
  metadata:
   name: alweterpod
   labels:
     app: alweter 
  spec: 
    containers:
    - name: alwetercontainer
      image: dockerpandian/project
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: alwetersvc
spec:
  type: LoadBalancer
  selector:
   app: alweter
  ports:
   - port: 80
     targetPort: 8080
